### ISSUE TITLE
Add a progress bar

### ISSUE THREAD

**Issue by luyckxn** [Calvagone/campsis#28]
It would be great to have a progress bar that indicates the progress in the simulation:
- How many subjects were simulated
- Remaining time (ETA)
- How many replicates were simulated
- Possibly a percentage

**Comment by mattfidler** [comment]
`rxode2` and `RxODE` has a progress bar already.  You could solve with `nDisplayProgress=1`.  See https://nlmixrdevelopment.github.io/RxODE/reference/rxSolve.html

Note `RxODE` is moving toward `rxode2`.  `nlmixr2`'s estimation functions can now be used in this new release.  Because this changes so much and to make sure people know that comparability may be a little different, we are renaming the packages.

**Comment by mattfidler** [comment]
You could also use`rxProgress()` for the progress bar

**Comment by mattfidler** [comment]
`rxProgress()` is independent of the method you use.

**Comment by mattfidler** [comment]
There is also https://github.com/r-lib/progress

**Comment by luyckxn** [comment]
Thanks. This is exactly what I need. As RxODE and mrgsolve are 'suggested' packages in the DESCRIPTION file of Campsis, I have a preference to import a third-party library like progress. This way, RxODE is not needed for the progress bar to work if mrgsolve is used.

I will implement it in the next release (campsis v1.2.1).
