### ISSUE TITLE
Add a new engine or change an engine to allow `rxode2` and `RxODE`

### ISSUE THREAD

**Issue by mattfidler** [Calvagone/campsis#92]
Related to #90

`rxode2` has been released on CRAN, so you could add another engine for `rxode2` quite easily.  

I am unsure when Wenping will submit a new RxODE, though the current one can be installed with recompilation only, ie

```r
install.packages("RxODE", type="source")
```

And everything should work.

**Comment by luyckxn** [comment]
Thanks Matt. I now install RxODE from the sources in the continuous integration with Github actions and it works fine.

**Comment by mattfidler** [comment]
That is great!

**Comment by luyckxn** [comment]
Hi Matt, do you have any idea when a new version of RxODE will be submitted to CRAN ? I'm having issues to submit a new version of campsis on CRAN because of RxODE, which is not working on Mac.

**Comment by mattfidler** [comment]
I do not know.  I am not the maintainer.  However, you could use:

https://github.com/Calvagone/campsismod/pull/52

https://github.com/Calvagone/campsis/pull/98

to use `rxode2`

**Comment by luyckxn** [comment]
Thanks a lot for your pull requests. I need to have a discussion with my colleagues next week.

For backwards compatibility and reproducibility reasons (especially for the simulation projects we worked on), it may be in our interest to keep the 'RxODE' engine.

What I will be probably do is:
- add a third engine rxode2 like you've done but keep the old engine RxODE
- put **rxode2** as the **default** simulation engine in Campsis instead of RxODE
- rework the tests a little (instead of duplicating the tests for each simulation engine, tests will be run based on the engines we'd like to test. At the end, the simulation results should be the same whatever the engine chosen...).
- in the DESCRIPTION file, suggested packages will be RxODE, rxode2 and mrgsolve.

**Comment by mattfidler** [comment]
That sounds fine, I thought you may need it to get to CRAN, so the easiest was to simply replace RxODE with rxode2 with a few version fixes.

**Comment by luyckxn** [comment]
Hi Matt, I could successfully submit campsis v1.3.0 to CRAN. As previously mentionned, rxode2 is now the default engine in Campsis (when argument 'dest' is not specified). Simulation tests on CRAN currently run with both rxode2 and mrgsolve. RxODE has been temporarily disabled in tests. Once it will work again on Mac, I'll probably re-enable it in the tests of CRAN. Thanks to the test refactoring, we can now choose the engines to be tested (see variable testEngines in testUtils.R). Please let me know when you think there will be breaking changes in rxode2 for campsis.

**Comment by mattfidler** [comment]
Ok. Thank you
